# Generated by Django 3.2 on 2021-05-01 06:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='remainder',
        ),
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='webapp.category', verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField(max_length=2000, verbose_name='Отзыв')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('moderation', models.BooleanField(default=False, verbose_name='Отмодерирован')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='webapp.goods', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'review',
            },
        ),
    ]
